### ISSUE TITLE
Add Oslo Bysykkel bike sharing network

### ISSUE THREAD

**Issue by tuxayo** [eskerda/pybikes#124]
It doesn't seem to be supported and there is already a Python package that access it https://pypi.python.org/pypi/oslobysykkel/

Has the support of this network been considered before?

**Comment by abadabanades** [comment]
Hi, I have been investigating a bit, The package you mention is completely outdated, since the API has changed.
I found an endpoint with the stations in their new website: https://oslobysykkel.no/api/internal/stations
```json
{"stations":[{"title":"Arkitekt Rivertz Plass",
              "subtitle":"i Uelands gate",
              "ready":true,
              "center": { "latitude": 59.934934,
                           "longitude": 10.749475}
             },
             {"title": "...",
              ...
```
However, the available bikes and free spots seem missing; instead the "ready" field appears: I guess it states whether an station has enough bikes available (who knows where is the threshold). Any idea where to find it? It seems it was available in the previous version

**Comment by eskerda** [comment]
: /

Their mobile app does not even seem to work without a registered telephone number

:-1:

**Comment by eskerda** [comment]
They used to have an spec available at http://smartbikeportal.clearchannel.no/public/mobapp/maq.asmx

**Comment by eskerda** [comment]
Seems `Snart Klart` most probably means `planned station`

**Comment by eskerda** [comment]
Ok, found this: http://oslo.map.webservice.sharebike.com:8888/

**Comment by eskerda** [comment]
This is even more interesting

http://oslo.map.webservice.sharebike.com:8888/json/MapService/LiveStationData?APIKey=A97C2382-BA61-432F-9518-060DE2C208C6&SystemID=cityoslo

**Comment by eskerda** [comment]
Not sure how down the rabbit hole we need to go

**Comment by eskerda** [comment]
Jackpot: https://oslobysykkel.no/api/v1/stations/availability

**Comment by tuxayo** [comment]
Great find! (I understand it's feasible?)

**Comment by eskerda** [comment]
Whilst this is technically feasible, this is a private endpoint. Emailed them about it, assumedly they told me it's going to be opened soon.

**Comment by willosof** [comment]
They said "within the week" to me over a month ago. Anyways. In the meanwhile - i found the same stuff you guys found (using the app and https MITM attack) and made a simple module for node.js:
https://www.npmjs.com/package/oslobysykkel

**Comment by eskerda** [comment]
> They said "within the week" to me over a month ago. 

How strange! Jokes aside, I hadn't my hopes up either. Thing is, our stance on this is clear. We do not target private endpoints anymore. Opening a private endpoint means hiding the reality, which is a city council or a PPP not complying with the open data kool-aid.

We should find a way to list these cases on our website and somehow channel people to contact them and build pressure.

**Comment by tuxayo** [comment]
> We should find a way to list these cases on our website and somehow channel people to contact them and build pressure.

Sounds a good idea.

As one of the first thing people want to know when coming the website is if their city network is supported. Would adding a marker on the map with a tool-tip explaining the situation do the trick?

**Comment by arnabkd** [comment]
> We should find a way to list these cases on our website and somehow channel people to contact them and build pressure.

In terms of "pressuring" Oslobysykkel specifically, I don't think it would be fruitful **right now**. They are at the moment taking their first baby steps into running the citybike system for Oslo, and it would do more harm than good to force them to allocate resources to comply with open data policies (rather than actually improving the experience by adding new stations, rebalancing bikes, researching usage patterns).  

But in general, yes I agree that this is a good idea.

Disclaimer: I am an avid user of Oslo bysykkel, so I am speaking mostly from a enduser pov and not necessarily from a developer pov.

**Comment by willosof** [comment]
They will be adding per app authentication to their currently unreleased
api in september :) until then it's "open".

William
tir. 31. mai 2016 kl. 12.06 skrev Arnab Datta <notifications@github.com>:

**Comment by eskerda** [comment]
> They will be adding per app authentication to their currently unreleased api in september :) until then it's "open".

That sounds good!

**Comment by arnabkd** [comment]
Update:
They posted some documentation of their API.
https://developer.oslobysykkel.no/api

**Comment by geirarne** [comment]
Hi! I'm product manager for Oslo City Bike, among other things overseeing our public API. Anything we can do to help out?

**Comment by olavxxx** [comment]
Hello, I found this project via home-assistant today and I threw together Oslo Bysykkel and Bergen Bysykkel. My PR is here: https://github.com/eskerda/pybikes/pull/268

**Comment by olavxxx** [comment]
This can now be closed @eskerda
