### ISSUE TITLE
Add Cincy Red Bike

### ISSUE THREAD

**Issue by doug-wade** [eskerda/pybikes#150]
Add a feed for http://www.cincyredbike.org/

**Comment by edumucelli** [comment]
@doug-wade the system that manages Cincy Redbike has been implemented, it is BCycle. The problem here is that there is no obvious (public) way to extract the amount of bicycle and bicycle stations from their page.

Their Android/iPhone app do offer those information, but, as aforementioned, it seems a private endpoint.

If you have any insights, that'd great. Cheers!

**Comment by eskerda** [comment]
Red bike, as part of all bcycle systems, has a GBFS feed available:

https://gbfs.bcycle.com/bcycle_cincyredbike/gbfs.json

More info: https://github.com/NABSA/gbfs

**Comment by eskerda** [comment]
This is related to this issue: https://github.com/eskerda/pybikes/issues/140

I will create a GBFS parser and move all possible feeds to that

**Comment by eskerda** [comment]
https://github.com/eskerda/pybikes/pull/195
