### ISSUE TITLE
Certain nextbike stations are not provided

### ISSUE THREAD

**Issue by jeweloper** [eskerda/pybikes#225]
Certain nextbike stations are currently not provided or mapped.
Here are three examples I found in the data source[nextbike-live.xml](https://nextbike.net/maps/nextbike-live.xml), but not provided/mapped on citybik.es:
- place with uid 50342 ("Dahlhausen Bahnhof")
- place with uid 2278899 ("Grünstr. 59 b ")
- place with uid 115213 ("Frohnhauser Platz")

Unlike all of the other place items, the ones affected are holding a additional property called "bike".
Is this maybe the reason these items are not correctly processed?

**Comment by eskerda** [comment]
As far as I know, these represent separate bikes and not real stations and thus are, right now, ignored, since we do not have a correct representation for bikes on systems (yet). For that particular issue, there's this thread https://github.com/eskerda/pybikes/issues/190

Anyway, I will check again just to make sure these are bikes and not real stations.

Thanks for reporting

**Comment by jeweloper** [comment]
One of the listed stations is in my neighborhood. It is a real station with 5 slots and a terminal. And it is in order. I've rented there a bike just yesterday.
The two others are also mapped on the [providers map](http://www.metropolradruhr.de/en/locations/). (You can find the stations by searching only by its first part/word of the station name. -> "Dahlhausen", "Grünstr" and "Frohnhauser")
Thx for your investigation.

**Comment by jeweloper** [comment]
Nextbike fixed the failure for record 50342 and 115213. Both are now mapped on citybik.es. Record 2278899 is a single bike and not a real station.

**Comment by eskerda** [comment]
@jeweloper awesome, thanks!
