### ISSUE TITLE
JESI BIKE SHARING POSITIONS

### ISSUE THREAD

**Issue by ghost** [eskerda/pybikes#249]
I live in Jesi where there are 4 bike sharing positions but they are wrong-collocated. Can I fix this issue? Or can you fix this issue?

**Comment by eskerda** [comment]
Hello @ANDREASBCA , we currently collect the data from this endpoint: http://www.bicincitta.com/citta_v3.asp?id=58&pag=2

Is there another map with the correct positions?

**Comment by ANDREASBCA** [comment]
In this map positions are not correct! You have to check OpenstreetMap. 
The three wrong positions are:
-Jesi, Viale Cavallotti
-Jesi, Piazza Pergolesi
-Jesi, Stazione di Jesi
I've attached three pictures. I hope you will fix this problem but it is difficoult to explain in an e-mail. :(
![schermata 2017-05-05 alle 12 36 46](https://cloud.githubusercontent.com/assets/28397129/25742609/7cd5db7c-3190-11e7-98b8-a132707269de.png)
![schermata 2017-05-05 alle 12 37 01](https://cloud.githubusercontent.com/assets/28397129/25742610/7cd6345a-3190-11e7-97c4-3eac74407438.png)
![schermata 2017-05-05 alle 12 37 16](https://cloud.githubusercontent.com/assets/28397129/25742611/7cd6e1d4-3190-11e7-9a5f-320e823eabb1.png)

**Comment by eskerda** [comment]
One possible fix is to hardcode these on code, but I am a bit unsure of going that route. Seems the one that is most wrongly positioned is the second one, as it is marked on a different street on the canonical source.

Let me think on a solution and will update here.

**Comment by ANDREASBCA** [comment]
Yes, you are very friendly. Thank you so much, the Jesi bike-sharing is a small service, but if there are not right data, it will be used by anyone. :)

**Comment by traversaro** [comment]
Hi @ANDREASBCA , 
  I think that Comunicare srl (the italian company mantaining Bicinicitta) is the actual provider of the data that needs to correct the location of the bike sharing stations. 

You can try to get in contact with them using this form : http://www.bicincitta.com/contatti.asp .

**Comment by ANDREASBCA** [comment]
Hi! I’ve sent an email to Comunicare srl. I’ve also noticed that there are better datas here (http://bicincitta.tobike.it/frmLeStazioni.aspx?ID=73). The position is wrong also here, but the number of bike is correct here instead of in the other site.
Il giorno 05 mag 2017, alle ore 13:09, Silvio Traversaro <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hi @ANDREASBCA<https://github.com/ANDREASBCA> ,
I think that Comunicare srl (the italian company mantaining Bicinicitta) is the actual provider of the data that needs to correct the location of the bike sharing stations.

You can try to get in contact with them using this form : http://www.bicincitta.com/contatti.asp .

**Comment by eskerda** [comment]
> Hi! I’ve sent an email to Comunicare srl. I’ve also noticed that there are better datas here (http://bicincitta.tobike.it/frmLeStazioni.aspx?ID=73). The position is wrong also here, but the number of bike is correct here instead of in the other site.

We can use this other feed url if needed. The correct numbers are on bicincitta.tobike.it, 100%?

![image](https://cloud.githubusercontent.com/assets/208952/25956940/67847742-366d-11e7-9100-3a0816a7e363.png)

**Comment by ANDREASBCA** [comment]
Yes, they are! ASCOLI's bike sharing isn't now working so that URL is the best one both for JESI and ASCOLI!

Andrea

Il giorno 11 mag 2017, alle ore 17:16, eskerda <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hi! I’ve sent an email to Comunicare srl. I’ve also noticed that there are better datas here (http://bicincitta.tobike.it/frmLeStazioni.aspx?ID=73). The position is wrong also here, but the number of bike is correct here instead of in the other site.

We can use this other feed url if needed. The correct numbers are on bicincitta.tobike.it<http://bicincitta.tobike.it>, 100%?

[image]<https://cloud.githubusercontent.com/assets/208952/25956940/67847742-366d-11e7-9100-3a0816a7e363.png>

**Comment by eskerda** [comment]
Just checking, we are already using the right feed for ascoli: http://bicincitta.tobike.it/frmLeStazioni.aspx?ID=73

We can move jesi to using this feed: http://bicincitta.tobike.it/frmLeStazioni.aspx?ID=236

**Comment by eskerda** [comment]
@ANDREASBCA Moved jesinbici feed to using http://bicincitta.tobike.it/frmLeStazioni.aspx?ID=236

Will you update me in case bicincitta contacts you back?

**Comment by ANDREASBCA** [comment]
Ok! Now datas are correct! :)
The only problem is the bike position. I've sent an e-mail about that and if they answer me, I'll let you know.
Best regards,

Andrea

Il giorno 13 mag 2017, alle ore 14:46, eskerda <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@ANDREASBCA<https://github.com/andreasbca> Moved jesinbici feed to using http://bicincitta.tobike.it/frmLeStazioni.aspx?ID=236

Will you update me in case bicincitta contacts you back?

**Comment by eskerda** [comment]
Hope this issue with the position and stats of stations has been since solved. Although by looking at the data it seems the system is dead.
