### ISSUE TITLE
Investigate nextbike

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#387]
Some networks are returning empty results: siedlecki-rower-miejski-siedlce

**Comment by kospl** [comment]
`nextbike-vinnytsia` returns empty stations list, see https://github.com/eskerda/citybikes-api/issues/24

**Comment by Altonss** [comment]
On the update of the nextbike data done here https://github.com/eskerda/pybikes/pull/425 this siedlecki network has been removed, probably not existing anymore :)

**Comment by Altonss** [comment]
Personally, I think that even networks with less than 3 stations might be usefull for some users.
Maintaining those systems could simply be done by people who need these systems and who would notify any change.
But what I also noticed, is that a lot of system have closed. This will probably happen less in the future, because the not very used systems have probably been removed by nextbike.
Moreover, I am thinking about a system to track all the systems of pibykes that are not working, by detecting them automatically. This would simplify the maintaining task :)
