### ISSUE TITLE
Add / check smoove systems

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#97]
This page lists all systems provided by smoove: http://www.smoove-bike.com/references

**Comment by edumucelli** [comment]
@eskerda, I've verified all the systems within Smoove. The statuses are the following:

0. France - Annemasse (not implemented, does not provide a map to extract the data: http://projet.smoove.fr/)
1. France - Avignon (works, "velopop" system)
2. France - Belfort (not implemented, does not provide a map to extract the data: http://optymo.fr/velo-libre-service/les-stations)
3. France - Chalon-sur-Saône ("reflex-grandchalon" does not work anymore. The site is not working anymore. As I have not found any news showing that the system has been turned off, I guess we can wait a bit to see if it gets back to work.)
4. France - Clermont-Ferrand (works, "c-velo" system)
5. France - Grenoble (not implemented, does not provide a map to extract the data: http://www.metrovelo.fr/fr/p-carte-des-stations.html)
6. France - Lorient (not implemented, although it provides the number of available bikes for 2 stations, it does not provide the number of free slots: http://www.lorient-velo.fr/sag_vls_stations.html)
7. France - Montpellier (not implemented, seems that data can be extracted from http://tam.cartographie.pro/)
8. France - Nice (works, "velobleu" implemented on Veloway system)
9. France - Saint-Etienne (works, "velivert" system)
10. France - Strasbourg (not implemented, same as Lorient, provides the number of available bikes, but not the free slots: http://www.velhop.strasbourg.eu/sag_vls_stations.html)
11. France - Valence (works, "libelo" system)
12. UK - Slough (It is going to differ from the current implementation, It would be better to add it alone on its on, I will do that: https://www.cycleslough.com/hire/location/)
13. Georgia - Batumi (works, "batumvelo" system)
14. Greece - Corfou ("The city of Kerkyra, on Corfou Island, has planed to  set up its fisrt bke-sharing system in September 2010; Unfortunately, the project failed.")
15. Italia - Vicenza ("Smoove has equipped the city of Vicenza in Italy of a demonstration station in September 2011. 
Unfortunately the project has stopped")
16. Kazakhstan - Astana (works, "velobike" system implemented on its on)
17. Russia - Moscow (works, "velobike_ru" system implemented on its on)
18. Thailand - Bangkok (not implemented, there is no interactive map to get data from: http://www.cubike-chula.com/Mains/Map.aspx)
19. United States - Chicago (not implemented, differs from the current implementation. It would be better to add on its on: http://chicago.smoovebike.com/en)

For 6 and 10 we can implement it, even though they do not show the number of available bikes, like we do on Call-a-Bike. Be aware that it is not going to be a plug-an-play solution with the current code due to the HTML regex. Note to us: the 'Emplacements libres' part is not going to be there in the ``STATUS_RGX``, need to make this part of the regex optional!

I will start by doing 12 (UK Slough) and 19 (US Chicago). Then I will proceed to others.

**Comment by eskerda** [comment]
Not so sure about bike chicago. This 'Bike and Roll' system looks more like a kind of bike tour / rental. More info at http://bikechicago.com . We also already support a system in Chicago that has many stations (divvy bikes).

**Comment by edumucelli** [comment]
My opinion is that even though their service does provide a city-wide coverage and goes more towards tour than the other traditional systems, that should not be a factor to let it out. Besides, many cities already have multiple systems, e.g., Munchen, Berlin, Bath, Koln, Warsaw, Wien, Sao Paulo, and I think if there are others more to add, there is no drawback, we are only enriching the lib.
